---
title: "Ring 아티팩트 제거"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---


1. https://sarepy.readthedocs.io/toc/section3_1/section3_1_1.html

2. 


## @Raven1998




사이노그램 $S[\theta,\,x]$ 에 대해 푸리에 변환

$$
\tilde{S}[u, v] = \mathfrak{F}[S[\theta, x]] 
$$

을 생각하자. 검출기 픽셀의 결함이 있다면 이것은 high frequency $u$ 의 spike 로 나타난다. 반면에 miscalibration 이 있다면 $u$ 의 넓은 영역에 걸쳐서 나타난다.  


버터워스(Butterworth) low-pass filter $H(u, v)$ 를 사용한다.


$$
H(u, v) = \left \{\begin{array}{ll} \dfrac{1}{1+ (u/u_0)^{2n}} \qquad & \text{if }|v|\le v_0 \\ 1 & \text{otherwise}\end{array}\right.
$$ {#eq-butterworth_low_pass_filter}


</br>




## @TITARENKO20101489 

하나의 사이노그램 $S[\theta, x]$ 를 생각하자. 이상적인 사이노그램은 연속이지만 실제 측정값은 이산적이므로 $s_{ij}= S[\theta_i, x_j]$ 라고 쓸 수 있다. 

여러 실험적 오차로 인해 샘플에 대해 원래 시노그램이 가져야 할 값 $s_{ij}$ 와 실제 측정된 값 $\tilde{s}_{ij}$ 사이에는 오차가 있다. 특히 링 아티팩트를 주는 픽셀마다의 불균일성이 원인이라면 그것은 $\theta_i$ 에 의존하지 않고 $x_j$ 에만 의존한다. 이것을 $q_j=q(x_j)$ 라고 하자. 즉

$$
\tilde{s}_{ij} = s_{ij} - q_j.
$$ {#eq-tirarenko2010_1}

</br> 

### Regulaized solution

우리는 $S[\theta,\,x]$ 가 매끄럽다고(원문에서는 smooth, 수학적인 의미에서 무한번 미분 가능하다는 의미에서의 smooth 인가?) 가정한다. Finite dimensional approxmation 에 따라 아래와 같이 정해지는 functional $G[q]$ 를 최소화 해야 한다.

$$
G[q] = \sum_{i=1}^{N_\theta} \sum_{j=1}^{N_x} \left| s_{ij}- s_{i, j+1}\right|^2 = \sum_{i=1}^{N_\theta} \sum_{j=1}^{N_x} \left| \tilde{s}_{ij} = \tilde{s}_{i, j+1} + q_j - q_{j+1}\right|^2
$$ {#eq-tirarenko2010_2}

여기서 $N_\theta$ 는 회전각의 갯수이며 $N_x$ 는 픽셀의 갯수이다. 여기서 해 $q= \begin{bmatrix} q_1 & \cdots & q_{N_x}\end{bmatrix}^T$ 는 유일하지 않은데 임의의 상수 $c$ 에 대해 $G[q] = G[q+c]$ 이기 때문이다. 

여기서 regularization 을 사용하는데 $q$ 는 기본적으로 실험 오차를 나타내므로 

$$
N_\theta \|q\|^2 = N_\theta \left(\sum_{j} |q_j|^2\right)
$$ 

를 최소화 하도록 한다. 즉 우리가 최소화 하는것은 $G[q]$ 가 아니라 어떤 regularization parameter $\lambda$ 에 대해 

$$
M_\lambda [q] = G[q] + \lambda N_q \|q\|^2
$$

를 최소화 하는 $\lambda$ 를 찾는다. 이 때 당연히 $\lambda > 0$ 이어야 한다.


